"""update rating

Revision ID: 0d8ccc900b61
Revises: 55b72fdb8d3b
Create Date: 2024-03-10 12:17:20.632621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8ccc900b61'
down_revision: Union[str, None] = '55b72fdb8d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###
