"""add_json_columns

Revision ID: 144a96c47d22
Revises: d518431b1aa7
Create Date: 2024-03-09 13:18:34.991725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144a96c47d22'
down_revision: Union[str, None] = 'd518431b1aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_json', sa.JSON(), nullable=True))
    op.add_column('picture', sa.Column('picture_edited_json', sa.JSON(), nullable=True))
    op.add_column('picture', sa.Column('qr_code_picture', sa.String(length=255), nullable=True))
    op.add_column('picture', sa.Column('qr_code_picture_edited', sa.String(length=255), nullable=True))
    op.drop_column('picture', 'qr_code_original_picture')
    op.drop_column('picture', 'picture_name')
    op.drop_column('picture', 'qr_code_edited_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('qr_code_edited_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('picture', sa.Column('picture_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('picture', sa.Column('qr_code_original_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('picture', 'qr_code_picture_edited')
    op.drop_column('picture', 'qr_code_picture')
    op.drop_column('picture', 'picture_edited_json')
    op.drop_column('picture', 'picture_json')
    # ### end Alembic commands ###
