"""Init

Revision ID: 1afcf54cc3e8
Revises: 
Create Date: 2024-03-01 15:08:20.010515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1afcf54cc3e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('picture_user_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'user', ['user_id'], ['id'])
    op.drop_column('picture', 'picture_url')
    op.drop_column('picture', 'created_at')
    op.drop_column('picture', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('picture', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('picture', sa.Column('picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key('picture_user_id_fkey', 'picture', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
