"""comment models

Revision ID: 2d6d011af6a1
Revises: dfe9eef98133
Create Date: 2024-03-03 12:49:09.673889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6d011af6a1'
down_revision: Union[str, None] = 'dfe9eef98133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'updated_at')
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
