"""add picture_name to table Picture

Revision ID: 322f65051d41
Revises: 4ad69ce83cef
Create Date: 2024-03-04 17:29:47.340708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322f65051d41'
down_revision: Union[str, None] = '4ad69ce83cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'picture_name')
    # ### end Alembic commands ###
