"""picture and user update

Revision ID: 48954fab42a1
Revises: 6728932871fb
Create Date: 2024-03-04 21:01:54.864393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48954fab42a1'
down_revision: Union[str, None] = '6728932871fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'picture_name')
    # ### end Alembic commands ###
