"""update picture

Revision ID: 55b72fdb8d3b
Revises: e2c4ebc03bec
Create Date: 2024-03-10 11:41:32.133368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b72fdb8d3b'
down_revision: Union[str, None] = 'e2c4ebc03bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
