"""qr_codes

Revision ID: 5a67903a7d53
Revises: ce05737cd946
Create Date: 2024-03-08 22:13:10.888058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a67903a7d53'
down_revision: Union[str, None] = 'ce05737cd946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('qr_code', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('qr_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'qr_code')
    op.drop_column('picture', 'qr_code')
    # ### end Alembic commands ###
