"""added_on_delete_cascade_to_some_tables

Revision ID: 93b70987baf6
Revises: a20921d0fee1
Create Date: 2024-03-10 17:27:41.751028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b70987baf6'
down_revision: Union[str, None] = 'a20921d0fee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_picture_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'picture', ['picture_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rating_picture_id_fkey', 'rating', type_='foreignkey')
    op.drop_constraint('rating_user_id_fkey', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rating', 'picture', ['picture_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reactions_comment_id_fkey', 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key('reactions_comment_id_fkey', 'reactions', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_user_id_fkey', 'rating', 'user', ['user_id'], ['id'])
    op.create_foreign_key('rating_picture_id_fkey', 'rating', 'picture', ['picture_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('comment_picture_id_fkey', 'comment', 'picture', ['picture_id'], ['id'])
    # ### end Alembic commands ###
