"""fix_picture_model

Revision ID: 9823fc072f4f
Revises: c802a7bca698
Create Date: 2024-03-02 12:13:22.110002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9823fc072f4f'
down_revision: Union[str, None] = 'c802a7bca698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_url_eddited', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'picture_url_eddited')
    # ### end Alembic commands ###
