"""pictures_with_description

Revision ID: b4fc1efc84ef
Revises: c2082ca6ef35
Create Date: 2024-02-29 20:50:32.961881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fc1efc84ef'
down_revision: Union[str, None] = 'c2082ca6ef35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_url', sa.String(length=255), nullable=False))
    op.add_column('picture', sa.Column('description', sa.String(), nullable=True))
    op.add_column('picture', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('picture_user_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key('picture_user_id_fkey', 'picture', 'user', ['user_id'], ['id'])
    op.drop_column('picture', 'created_at')
    op.drop_column('picture', 'description')
    op.drop_column('picture', 'picture_url')
    # ### end Alembic commands ###
