"""Fix alembic with pictures model updated

Revision ID: c802a7bca698
Revises: 1afcf54cc3e8
Create Date: 2024-03-01 18:20:11.214036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c802a7bca698'
down_revision: Union[str, None] = '1afcf54cc3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('picture_url', sa.String(length=255), nullable=False))
    op.add_column('picture', sa.Column('description', sa.String(), nullable=True))
    op.add_column('picture', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('picture_user_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key(None, 'picture', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picture', type_='foreignkey')
    op.create_foreign_key('picture_user_id_fkey', 'picture', 'user', ['user_id'], ['id'])
    op.drop_column('picture', 'created_at')
    op.drop_column('picture', 'description')
    op.drop_column('picture', 'picture_url')
    # ### end Alembic commands ###
