"""updated picture qr_codes

Revision ID: d518431b1aa7
Revises: 5a67903a7d53
Create Date: 2024-03-08 22:36:33.338275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd518431b1aa7'
down_revision: Union[str, None] = '5a67903a7d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('qr_code_original_picture', sa.String(length=255), nullable=True))
    op.add_column('picture', sa.Column('qr_code_edited_picture', sa.String(length=255), nullable=True))
    op.drop_column('picture', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('qr_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('picture', 'qr_code_edited_picture')
    op.drop_column('picture', 'qr_code_original_picture')
    # ### end Alembic commands ###
